apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "rabbitmq.fullname" . }}
  labels:
    app: {{ template "rabbitmq.fullname" . }}
    chart: {{ template "rabbitmq.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  podSelector:
    matchLabels:
      app: {{ template "rabbitmq.fullname" . }}
      release: {{ .Release.Name }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          rabbitmq-client: "true"
    ports:
    - protocol: TCP
      port: 5672
    - protocol: TCP
      port: 15672
  - from:
    - namespaceSelector: {}
    - podSelector:
        matchLabels:
          app: "prometheus"
    ports:
    - protocol: TCP
      port: 9419
  egress: []
