apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "partner-server.fullname" . }}-hutch
  labels:
    app: {{ template "partner-server.name" . }}-hutch
    chart: {{ template "partner-server.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicas.hutch }}
  affinity:
    {{- include "partner-server.affinity" . | indent 4}}
  selector:
    matchLabels:
      app: {{ template "partner-server.name" . }}-hutch
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "partner-server.name" . }}-hutch
        release: {{ .Release.Name }}
        rabbitmq-client: "true"
        partner-worker: "true"
    spec:
      initContainers:
        - name: wait-for-migrate
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["bin/wait_to_migrate"]
          {{ include "partner-server.env" . | indent 10 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["bundle", "exec", "hutch"]
          {{ include "partner-server.env" . | indent 10 }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
        {{- include "partner-redis-stunnel-container" . | indent 8 }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
