apiVersion: v1
kind: Service
metadata:
  name: {{ template "partner-server.fullname" . }}-web
  labels:
    app: {{ template "partner-server.name" . }}-web
    chart: {{ template "partner-server.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "partner-server.name" . }}-web
    release: {{ .Release.Name }}
