apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "shared-services.fullname" . }}-grafana-prometheus-datasource
  labels:
    app: {{ template "shared-services.name" . }}
    chart: {{ template "shared-services.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    grafana_datasource: "true"
data:
  datasource.yaml: |-
      apiVersion: 1
      deleteDatasources:
        - name: Graphite
          orgId: 1
      datasources:
        - name: prometheus
          type: prometheus
          orgId: 1
          access: proxy
          url: http://shared-services-prometheus-server:80
