{
 "title": "Kubernetes",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "Node",
    "query": "label_values(kubernetes_io_hostname)"
   },
   {
    "name": "Role",
    "query": "label_values(kubernetes_io_role)"
   },
   { "name": "Namespace", "query": "label_values(namespace)" }
  ]
 },
 "panels": [
  { "title": "Containers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pods CPU usage ($interval avg)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\",kubernetes_io_role=~\"^$Role$\",namespace=~\"^$Namespace$\"}[$interval])) by (pod_name) > .005",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Pods memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\",kubernetes_io_role=~\"^$Role$\",namespace=~\"^$Namespace$\"}) by (pod_name) > (20 * 1024 * 1024)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Node Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum (container_memory_working_set_bytes{id=\"/\",kubernetes_io_role=~\"^$Role$\",kubernetes_io_hostname=~\"^$Node$\"}) by (kubernetes_io_hostname)) / (sum (machine_memory_bytes{kubernetes_io_role=~\"^$Role$\",kubernetes_io_hostname=~\"^$Node$\"}) by (kubernetes_io_hostname)) * 100",
     "legendFormat": "{{ kubernetes_io_hostname }}"
    }
   ]
  },
  {
   "title": "Node CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum (rate (container_cpu_usage_seconds_total{id=\"/\",kubernetes_io_role=~\"^$Role$\",kubernetes_io_hostname=~\"^$Node$\"}[$interval])) by (kubernetes_io_hostname)) / (sum (machine_cpu_cores{kubernetes_io_role=~\"^$Role$\",kubernetes_io_hostname=~\"^$Node$\"}) by (kubernetes_io_hostname)) * 100",
     "legendFormat": "{{ kubernetes_io_hostname }}"
    }
   ]
  },
  {
   "title": "AWS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Data Store Free Memory",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "aws_rds_freeable_memory_minimum",
       "legendFormat": "{{ dbinstance_identifier }}"
      },
      {
       "expr": "aws_es_free_storage_space_minimum * 1024 * 1024",
       "legendFormat": "{{ domain_name }}"
      },
      {
       "expr": "aws_elasticache_freeable_memory_minimum",
       "legendFormat": "{{ cache_cluster_id }}"
      }
     ]
    },
    {
     "title": "Data Store CPU Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "aws_rds_cpuutilization_maximum{}",
       "legendFormat": "{{ dbinstance_identifier }}"
      },
      {
       "expr": "aws_elasticache_cpuutilization_maximum{}",
       "legendFormat": "{{ cache_cluster_id }}"
      },
      {
       "expr": "aws_es_cpuutilization_maximum{}",
       "legendFormat": "{{ domain_name }}"
      }
     ]
    },
    {
     "title": "RDS Database Connections",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "aws_rds_database_connections_maximum{}",
       "legendFormat": "{{ dbinstance_identifier }}"
      },
      { "expr": "awsconnection" }
     ]
    },
    {
     "title": "ES JVM Memory Pressure",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 31 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "aws_es_jvmmemory_pressure_maximum",
       "legendFormat": "{{ domain_name }}"
      }
     ]
    },
    {
     "title": "EBS Burst Balance",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      { "expr": "aws_ebs_burst_balance_minimum", "legendFormat": "{{ volume_id }}" }
     ]
    },
    {
     "title": "EBS Volume iops",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 36 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "aws_ebs_volume_read_ops_maximum",
       "legendFormat": "{{ volume_id }} read"
      },
      {
       "expr": "aws_ebs_volume_read_ops_maximum",
       "legendFormat": "{{ volume_id }} write"
      }
     ]
    },
    {
     "title": "CPU Credit Balance",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "aws_ec2_cpucredit_balance_minimum",
       "legendFormat": "{{ instance_id }}"
      },
      {
       "expr": "aws_rds_cpucredit_balance_minimum",
       "legendFormat": "{{ dbinstance_identifier }}"
      }
     ]
    }
   ]
  },
  { "title": "Application", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "RabbitMQ Stats",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rabbitmq_connectionsTotal", "legendFormat": "connections" },
    { "expr": "rabbitmq_channelsTotal", "legendFormat": "channels" },
    { "expr": "rabbitmq_consumersTotal", "legendFormat": "consumers" }
   ]
  },
  {
   "title": "RabbitMQ  Messages [$interval]",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(rabbitmq_queue_messages_published_total[$interval]) > 0",
     "legendFormat": "Pub: {{release}} - {{queue}}"
    },
    {
     "expr": "rate(rabbitmq_queue_messages_delivered_total[$interval]) > 0",
     "legendFormat": "Ack: {{release}} - {{queue}}"
    }
   ]
  },
  {
   "title": "Total Requests [$interval]",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(nginx_upstream_requests_total{upstream!=\"shared-services-shared-services-grafana-80\"}[$interval])",
     "legendFormat": "{{ upstream }}"
    },
    {
     "expr": "sum(rate(nginx_upstream_requests_total{upstream!=\"shared-services-shared-services-grafana-80\"}[$interval]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "5xx Requests [$interval]",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(nginx_upstream_responses_total{upstream!=\"shared-services-shared-services-grafana-80\",status_code=\"5xx\"}[$interval])",
     "legendFormat": "{{ upstream }}"
    }
   ]
  },
  {
   "title": "HTTP Response Average",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "nginx_upstream_response_msecs_avg{upstream!~\"upstream-default-backend|shared-services-shared-services-grafana-80\"}",
     "legendFormat": "{{ upstream }}"
    }
   ]
  },
  {
   "title": "Sidekiq Jobs [$interval]",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(sidekiq_processed_jobs_total[$interval])",
     "legendFormat": "processed: {{ app }}"
    },
    {
     "expr": "rate(sidekiq_failed_jobs_total[$interval])",
     "legendFormat": "failed: {{ app }}"
    },
    { "expr": "sidekiq_enqueued_jobs", "legendFormat": "queued: {{ app }}" }
   ]
  },
  {
   "title": "Container Terminations",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_terminated{container!~\"^redis-stunnel|acmesolver\"}) by (container) > 0",
     "legendFormat": "{{ container }}"
    }
   ]
  }
 ]
}