{{- $target := .Values.ingress.target -}}
apiVersion: v1
kind: Service
metadata:
  name: master-lighthouse-server 
  labels:
    app: {{ template "master-ingress.name" . }}
    chart: {{ template "master-ingress.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: lighthouse-server-web
    release: vineya-{{ $target }}
