{{- if or .Values.postgresql.enabled .Values.jobs.createDB -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "interpreter-server.fullname" . }}-db-create
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-2"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: {{ template "interpreter-server.name" . }}-db-create
      labels:
        app: {{ template "interpreter-server.name" . }}-db-create
        release: {{ .Release.Name }}
        rabbitmq-client: "true"
    spec:
      restartPolicy: Never
      containers:
        {{- include "interpreter-redis-stunnel-container" . | indent 8 }}
        - name: {{ .Chart.Name }}-db-create
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          workingDir: /code/apps/interpreter_server_web
          args: ["mix", "ecto.create"]
          {{ include "interpreter-server.env" . | indent 10 }}
{{- end -}}
