apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "interpreter-server.fullname" . }}-delete-index-version
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  activeDeadlineSeconds: 60
  template:
    metadata:
      name: {{ template "interpreter-server.name" . }}-delete-index-version
      labels:
        app: {{ template "interpreter-server.name" . }}-delete-index-version
        release: {{ .Release.Name }}

    spec:
      restartPolicy: Never
      containers:
        - name: {{ .Chart.Name }}-delete-index-version
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          workingDir: /code
          args: ["mix", "search.indices", "delete_version"]
          {{ include "interpreter-server.env" . | indent 10 }}
