{{- if .Values.jobs.fetchFrontend -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "lighthouse-server.fullname" . }}-fetch-frontend
  annotations:
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: {{ template "lighthouse-server.name" . }}-fetch-frontend
      labels:
        app: {{ template "lighthouse-server.name" . }}-fetch-frontend
        release: {{ .Release.Name }}
        lighthouse-worker: "true"
    spec:
      restartPolicy: Never
      containers:
        - name: {{ .Chart.Name }}-fetch-frontend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          args: ["sh", "-c", "set -x && sleep 5 && curl -v -X \"POST\" \"http://{{ template "lighthouse-server.fullname" . }}-web:$PORT/make/ember/current$(if [ ! -z \"$LIGHTHOUSE_DEPLOY_TOKEN\" ]; then echo \"?secret=$LIGHTHOUSE_DEPLOY_TOKEN\"; fi )\" -H \"Accept: text/html\""]
          {{ include "lighthouse-server.env" . | indent 10 }}
{{- end -}}
