##############################################################
# This file contains settings that apply to the prod 'green' #
# environment. It overrides defaults in the following        #
# - env/prod.common.yaml                                     #
# - vineya/values.yaml                                       #
##############################################################

##################
# Global Setting #
##################
global:
  color: green

#####################
# Lighthouse Server #
#####################
lighthouse-server:

  # Docker Image/Tag
  image:
    tag: v2.16.0

##################
# Partner Server #
##################
partner-server:

  # Docker Image/Tag
  image:
    tag: v2.16.0

######################
# Interpreter Server #
######################
interpreter-server:

  # Docker Image/Tag
  image:
    tag: v2.16.0
